
FROM ubuntu:bionic-20200112
RUN apt-get update
RUN apt-get upgrade -y

RUN apt-get install -y python3.7 python3.7-dev python3-venv python3.7-venv
RUN apt-get install -y coreutils vim-tiny iputils-ping iputils-tracepath less
RUN apt-get install -y ppp
RUN apt-get install -y iproute2 gcc

# for pyinstaller
RUN apt-get install -y rsync zlib1g-dev

ENV HOME /home/hologram

ADD hologramentry.bash /root/hologramentry.bash
RUN chmod a+rx /root/hologramentry.bash
ADD Dockerfile /root/Dockerfile
ENTRYPOINT ["/root/hologramentry.bash"]

# docker build -t hologramruntime .
# docker run -td --name hologram -v $(pwd)/hologram-python:/home/hologram/hologram-python -v $(pwd)/venv37:/root/venv37 hologramruntime

